// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyBQC0mSb2Fc1ESqCezH_UkPvVeaud2rArQ',
//     appId: '1:570564122610:web:f812b1a00e8d06a6113d6b',
//     messagingSenderId: '570564122610',
//     projectId: 'sesss-c24cf',
//     authDomain: 'sesss-c24cf.firebaseapp.com',
//     storageBucket: 'sesss-c24cf.appspot.com',
//     measurementId: 'G-EXE1SPYR1J',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAhk9xC8912_Ht2dCJVA3LdJrS2VrURLmY',
//     appId: '1:570564122610:android:b7392f4a06126079113d6b',
//     messagingSenderId: '570564122610',
//     projectId: 'sesss-c24cf',
//     storageBucket: 'sesss-c24cf.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBuHJe3ai1mXBMOXhYgEy0SgphT5T7mHMg',
//     appId: '1:570564122610:ios:99b94273331b6349113d6b',
//     messagingSenderId: '570564122610',
//     projectId: 'sesss-c24cf',
//     storageBucket: 'sesss-c24cf.appspot.com',
//     iosBundleId: 'com.example.srs5',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyBuHJe3ai1mXBMOXhYgEy0SgphT5T7mHMg',
//     appId: '1:570564122610:ios:99b94273331b6349113d6b',
//     messagingSenderId: '570564122610',
//     projectId: 'sesss-c24cf',
//     storageBucket: 'sesss-c24cf.appspot.com',
//     iosBundleId: 'com.example.srs5',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyBQC0mSb2Fc1ESqCezH_UkPvVeaud2rArQ',
//     appId: '1:570564122610:web:1987bc18c30d4463113d6b',
//     messagingSenderId: '570564122610',
//     projectId: 'sesss-c24cf',
//     authDomain: 'sesss-c24cf.firebaseapp.com',
//     storageBucket: 'sesss-c24cf.appspot.com',
//     measurementId: 'G-MB21085SSM',
//   );
// }
